site_name: Made With ML
site_url: ''
repo_url: https://github.com/YounessAm/Made-With-ML
nav:
  - Home: index.md
  - scripts:
    - config: madewithml/config.md
    - data: madewithml/data.md
    - models: madewithml/models.md
    - train: madewithml/train.md
    - tune: madewithml/tune.md
    - evaluate: madewithml/evaluate.md
    - predict: madewithml/predict.md
    - serve: madewithml/serve.md
    - utils: madewithml/util.md
theme: readthedocs
plugins:
  - mkdocstrings
watch:
  - .  # reload docs for any file changes
